import bcrypt from 'bcrypt'

// ! Hashing the password
const hashPassword = async (password) => {
  const salt = await bcrypt.genSalt(10)
  const hashedPassword = await bcrypt.hash(password, salt)
  return hashedPassword
}


// ! Default users
const users = { 
  admin: {
    email: 'admin@admin.com',
    userName: 'admin',
    password: await hashPassword('12345'),
    role: 'admin',
  },
  user: {
    email: 'user@email.com',
    userName: 'user',
    password: await hashPassword('12345'),
    role: 'user',
    _id: '0B8F639A9B8FEC5181656136',
  },
}


// ! Default movies
const movies = [
  {
    name: 'The Lion King',
    description:
      'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    directors: ['Rogers Allers', 'Rob Minkoff'],
    releaseYear: 1994,
    runtime: '1h 28m',
    tags: ['Adventure', 'Animal', 'Drama', 'Family', 'Musical'],
    avgUserRating: 0,
    imdbRating: 8.5,
    budget: '45 million USD',
    boxOffice: '$968.5 million',
    productionCompany: 'Walt Disney Pictures',
    posterImg:
      'https://www.movies4kids.co.uk/wp-content/uploads/2011/02/the-lion-king-524fb69e8c273.jpg',
    stills: {
      img1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnBgNO1T6_PoFdq6JQQQW4JOZZJjWipKJAF30h9jIptTcFSWNZ3x4ZH-GqBUEUvj8oT-8&usqp=CAU',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTgwMzE4OTE1Nl5BMl5BanBnXkFtZTYwMDUwMTQ3._V1_.jpg',
      img3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-1Oe-4ww-BzSzXdb6cPNugK1xklf7uhlsiA&usqp=CAU',
    },
    youtubeId: 'lFzVJEksoDY',
  },
  {
    name: 'The Lego Movie',
    description: 'An ordinary LEGO construction worker, thought to be the prophesied as "special", is recruited to join a quest to stop an evil tyrant from gluing the LEGO universe into eternal stasis.',
    cast: ['Chris Pratt', 'Will Ferrell', 'Elizabeth Banks'],
    directors: ['Phil Lord', 'Christopher Miller'],
    releaseYear: 2014,
    runtime: '1h 40m',
    tags: ['Action', 'Adventure', 'Fantasy', 'Toy', 'Sci-Fi'],
    avgUserRating: 0,
    imdbRating: 7.7,
    budget: '60 million USD',
    boxOffice: '$468.1 million',
    productionCompany: ['Warner Bros'],
    posterImg: 'https://m.media-amazon.com/images/I/8118cL0uL2L._AC_SY741_.jpg',
    stills: {
      img1: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-21.jpg',
      img2: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-11.jpg',
      img3: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-13.jpg',
    },
    youtubeId: 'fZ_JOBCLF-I',
    officialSite: 'https://www.warnerbros.com/movies/lego-movie',
  },
  {
    name: 'Akira',
    description: 'A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.',
    cast: ['Mitsuo Iwata', 'Nozomu Sasaki', 'Mami Koyama'],
    directors: ['Katsushiro Otomo'],
    releaseYear: 1988,
    runtime: '2h 4m',
    tags: ['Action', 'Anime', 'Drama', 'Fantasy', 'Sci-Fi', 'Thriller'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '¥700 million',
    boxOffice: '49 million USD',
    productionCompany: ['Tokyo Movie Shinsha'],
    posterImg: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/AKIRA_%281988_poster%29.jpg/220px-AKIRA_%281988_poster%29.jpg',
    stills: { 
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_006.jpg?bwg=1569515759',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_046.jpg?bwg=1569515756',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_043.jpg?bwg=1569515756',
    },
    youtubeId: 'nA8KmHC2Z-g',
  },
  {
    name: 'The Incredibles',
    description: 'While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.',
    cast: ['Craig Nelson', 'Samuel L. Jackson', 'Holly Hunter'],
    directors: ['Brad Bird'],
    releaseYear: 2004,
    runtime: '1h 55m',
    tags: ['Action', 'Adventure', 'Family', 'Sci-Fi'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '92 million USD',
    boxOffice: '631 million USD',
    productionCompany: ['Pixar Animations Studies', 'Walt Disney Pictures'],
    posterImg: 'https://3.bp.blogspot.com/-6pm0yLcFDqs/T-mjxClPnHI/AAAAAAAAHts/nonymvXfX6o/s1600/The+Incredibles+%282004%29+1.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/disney/images/4/47/Incredibles-disneyscreencaps.com-754.jpg',
      img2: 'https://static.wikia.nocookie.net/disney/images/4/49/Incredibles-disneyscreencaps.com-11411.jpg',
      img3: 'https://static.wikia.nocookie.net/disney/images/e/ef/Incredibles-disneyscreencaps.com-11903.jpg',
    },
    youtubeId: 'SOKY7XyOHTA',
    officialSite: 'https://www.pixar.com/feature-films/the-incredibles',
  },
  {
    name: 'Wall-E',
    description: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    cast: ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'],
    directors: ['Andrew Stanton'],
    releaseYear: 2008,
    runtime: '1h 38m',
    tags: ['Adventure', 'Family', 'Sci-Fi'],
    avgUserRating: 0,
    imdbRating: 8.4,
    budget: '180 million USD',
    boxOffice: '521 million USD',
    productionCompany: ['Pixar Animation Studios', 'FortyFour Studios', 'Walt Disney Pictures'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/f/f2/Walleposter.jpg',
    stills: {
      img1: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470764072845-47E0I36XDWT09S5AIN75/Walle11.jpg',
      img2: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470764122740-BZ0LLAHWICB1DU74N9RR/Eve12.jpg?format=1500w',
      img3: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470765942248-4QVAI3OTMZLPDO2KDXZ3/Humans10.jpg?format=1500w',
    },
    youtubeId: '4HaQgnPZ4Lo',
    officialSite: 'https://www.pixar.com/feature-films/walle',
  },
  {
    name: 'Perfect Blue',
    description: 'A pop singer gives up her career to become an actress, but she slowly goes insane when she starts being stalked by an obsessed fan and what seems to be a ghost of her past.',
    cast: ['Junko Iwao', 'Rica Matsumoto', 'Shinpachi Tsuji'],
    directors: ['Satoshi Kon'],
    releaseYear: 1997,
    runtime: '1h 21m',
    tags: ['Anime', 'Crime', 'Drama', 'Mystery', 'Thriller'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '¥3,000,000',
    boxOffice: '563,130 USD',
    productionCompany: ['Rex Entertainment', 'Kotobuki Seihan Printing', 'Asahi Broadcasting Corporation (ABC)'],
    posterImg: 'https://media-cache.cinematerial.com/p/500x/s1stmj3g/perfect-blue-movie-poster.jpg?v=1456615284',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_002.jpg?bwg=1569600824',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_041.jpg?bwg=1569600821',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_059.jpg?bwg=1569600821',
    },
    youtubeId: '4uRakM7gpo4',
  },
  {
    name: 'Grave of the Fireflies',
    description: 'A young boy and his little sister struggle to survive in Japan during World War II',
    cast: ['Tsutomu Tatsumi', 'Ayano Shiraishi', 'Akemi Yamaguchi'],
    directors: ['Isao Takahata'],
    releaseYear: 1988,
    runtime: '1h 29m',
    tags: ['Anime'],
    avgUserRating: 0,
    imdbRating: 8.5,
    budget: '3.7 million USD',
    boxOffice: '516,962 USD',
    productionCompany: ['Studio Ghibli', 'Shinchosha Company'],
    posterImg: 'https://static.wikia.nocookie.net/studio-ghibli/images/6/6d/Grave_of_the_Fireflies_poster.jpg',
    stills: {
      img1: 'https://cdni.fancaps.net/file/fancaps-movieimages/2295865.jpg',
      img2: 'https://cdni.fancaps.net/file/fancaps-movieimages/2295911.jpg',
      img3: 'https://cdni.fancaps.net/file/fancaps-movieimages/2296193.jpg',
    },
    youtubeId: '4vPeTSRd580',
    officialSite: 'https://www.ghibli.jp/works/hotarunohaka/',
  },
  {
    name: 'Nausicaa of the Valley of the Wind',
    description: 'Warrior and pacifist Princess Nausicaä desperately struggles to prevent two warring nations from destroying themselves and their dying planet.',
    cast: ['Sumi Shimamoto', 'Mahito Tsujimura', 'Hisako Kyoda'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1984,
    runtime: '1h 57m',
    tags: ['Anime', 'Adventure', 'Sci-Fi'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '1 million USD',
    boxOffice: '8.8 million USD',
    productionCompany: ['Production companies', 'NibarikiTokuma', 'ShotenHakuhodo'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BZTI3NmJmYTQtNDg4NS00M2VlLTgzZDAtZWIwZDcyOWY5YzIzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY1200_CR85,0,630,1200_AL_.jpg',
    stills: {
      img1: 'https://film-grab.com/2020/03/24/nausicaa-of-the-valley-of-the-wind/#bwg2197/137160',
      img2: 'https://film-grab.com/2020/03/24/nausicaa-of-the-valley-of-the-wind/#bwg2197/137143',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Nausica_065.jpg?bwg=1569499346',
    },
    youtubeId: '6zhLBe319KE',
  },
  {
    name: 'Ghost in the Shell',
    description: 'A cyborg policewoman and her partner hunt a mysterious and powerful hacker called the Puppet Master.',
    cast: ['Atsuko Tanaka', 'Iemasa Kayumi', 'Akio Ôtsuka'],
    directors: ['Mamoru Oshii'],
    releaseYear: 1995,
    runtime: '1h 23m',
    tags: ['Action', 'Anime', 'Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    avgUserRating: 0,
    imdbRating: 7.9,
    budget: '¥330,000,000',
    boxOffice: '918,738 USD',
    productionCompany: ['KôdanshaBandai', 'Visual Company', 'Manga Entertainment'],
    posterImg: 'https://www.scifi-movies.com/images/contenu/data/0000986/affiche-ghost-in-the-shell-1995-3.jpg',
    stills: {
      img1: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506035.jpg',
      img2: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506105.jpg',
      img3: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506429.jpg',
    },
    youtubeId: '8RF09G8Ymqg',
  },
  {
    name: 'Fantastic Mr. Fox',
    description: 'Devil-may-care Mr. Fox quits chicken thieving to start a family with Mrs. Fox, but twelve years later, he leaves his columnist job to rob poultry from three mean farmers who devise a plan to trap Fox and others in the burrowing animal community. With his friends and neighbors, Fox saves his animal community and beats the farmers at their own game.',
    cast: ['George Clooney','Meryl Streep', 'Bill Murray'],
    directors: ['Wes Anderson'],
    releaseYear: 2009,
    runtime: '1h 27m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Crime', 'Drama', 'Family'],
    avgUserRating: 0,
    imdbRating: 7.9,
    budget: '40 million USD',
    boxOffice: '46 million USD',
    productionCompany: ['Twentieth Century Fox', 'Indian Paintbrush', 'New Regency Productions'],
    posterImg: 'https://lumiere-a.akamaihd.net/v1/images/image_3cdae9ca.jpeg',
    stills: {
      img1: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51846',
      img2: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51813',
      img3: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51830',
    },
    youtubeId: 'n2igjYFojUo',
    officialSite: 'https://family.20thcenturystudios.com/movies/fantastic-mr-fox',
  },
  {
    name: 'Princess Mononoke',
    description: 'While protecting his village from a rampaging boar-god, the young warrior Ashitaka becomes afflicted with a deadly curse. To find the cure that will save his life, he journeys deep into sacred depths of the Great Forest Spirit\'s realm where he meets San (Princess Mononoke), a girl raised by wolves. It\'s not long before Ashitaka is caught in the middle of a battle between iron-ore prospecting humans and the forest dwellers. He must summon the spirit-powers and all his courage to stop man and nature from destroying each other.',
    cast: ['Yôji Matsuda', 'Yuriko Ishida', 'Yûko Tanaka'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1997,
    runtime: '2h 14m',
    tags: ['Anime', 'Adventure', 'Fantasy'],
    avgUserRating: 0,
    imdbRating: 8.4,
    budget: '¥2,400,000,000',
    boxOffice: '170 million USD',
    productionCompany: ['DENTSU Music And Entertainment', 'Nibariki', 'Nippon Television Network (NTV)'],
    posterImg: 'https://static.wikia.nocookie.net/studio-ghibli/images/c/c6/Princess_Mononoke.jpg',
    stills: {
      img1: 'https://film-grab.com/2020/04/20/princess-mononoke/#bwg2305/143290',
      img2: 'https://film-grab.com/2020/04/20/princess-mononoke/#bwg2305/143270',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Princess_Mononoke_055.jpg?bwg=1569601131',
    },
    youtubeId: '4OiMOHRDs14',
  },
  {
    name: 'Zootopia',
    description: 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    cast: ['Ginnifer Goodwin', 'Jason Bateman', 'Idris Elba'],
    directors: ['Byron Howard', 'Rich Moore', 'Jared Bush'],
    releaseYear: 2016,
    runtime: '1h 48m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Crime', 'Family', 'Mystery'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '150 million USD',
    boxOffice: '1 billion USD',
    productionCompany: ['Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_.jpg',
    stills: {
      img1: 'https://s.movieinsider.com/images/p/274366_m1448424117.jpg',
      img2: 'https://images.fandango.com/r1.0.1039/ImageRenderer/1040/650/redesign/areas/movie/moviesubpages/img/noimage_900x900.jpg/183935/images/masterrepository/fandango/183935/zootopia-ps-11.jpg',
      img3: 'https://s.movieinsider.com/images/p/274368_m1448424186.jpg',
    },
    youtubeId: 'jWM0ct-OLsM',
    officialSite: 'https://disneyanimation.com/films/zootopia/',
  },
  {
    name: 'Paprika',
    description: 'When a machine that allows therapists to enter their patients\' dreams is stolen, all hell breaks loose. Only a young female therapist, Paprika, can stop it.',
    cast: ['Megumi Hayashibara', 'Tôru Emori', 'Katsunosuke Hori'],
    directors: ['Satoshi Kon'],
    releaseYear: 2006,
    runtime: '1h 30m',
    tags: ['Drama', 'Fantasy', 'Mystery', 'Sci-Fi', 'Thriller'],
    avgUserRating: 0,
    imdbRating: 7.7,
    budget: '¥300,000,000',
    boxOffice: '946,590 million USD',
    productionCompany: ['Madhouse', 'Sony Pictures Entertainment'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNDI4MGEwZDAtZDg0Yy00MjFhLTg1MjctODdmZTMyNTUyNDI3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
    stills: {
      img1: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-134.jpg',
      img2: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-011.jpg',
      img3: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-002.jpg',
    },
    youtubeId: 'PIUqozzyW2k',
    officialSite: 'https://www.sonypictures.com/movies/paprika',
  },
  {
    name: 'Waltz with Bashir',
    description: 'An Israeli film director interviews fellow veterans of the 1982 invasion of Lebanon to reconstruct his own memories of his term of service in that conflict.',
    cast: ['Ari Folman', 'Ron Ben-Yishai', 'Ronny Dayag'],
    directors: ['Ari Folman'],
    releaseYear: 2008,
    runtime: '1h 30m',
    tags: ['Documentary', 'Biography', 'Drama', 'History', 'Mystery', 'War'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '1.5 million USD',
    boxOffice: '11 million USD',
    productionCompany: ['Bridgit Folman Film Gang', 'Les Films d\'Ici', 'Razor Film Produktion GmbH'],
    posterImg: 'https://cdn.posteritati.com/posters/000/000/027/594/waltz-with-bashir-md-web.jpg',
    stills: {
      img1: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-11.jpg',
      img2: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-3.jpg',
      img3: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-7.jpg',
    },
    youtubeId: 'XbXdwBNkCmk',
    officialSite: 'https://www.sonypictures.com/movies/waltzwithbashir',
  },
  {
    name: 'Laputa: Castle in the Sky',
    description: 'A young boy and a girl with a magic crystal must race against pirates and foreign agents in a search for a legendary floating castle.',
    cast: ['Mayumi Tanaka', 'Keiko Yokozawa', 'Kotoe Hatsui'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1986,
    runtime: '2h 5m',
    tags: ['Anime', 'Adventure', 'Family', 'Fantasy'],
    avgUserRating: 0,
    imdbRating: 8,
    budget: '3.3 million USD',
    boxOffice: '6.1 million USD',
    productionCompany: ['Tokuma Shoten', 'Studio Ghibli'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNDFhZmY2NTgtMzljYy00MTlhLTgyMjItNTEwZWJkYThhYzkyXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_.jpg',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_002.jpg?bwg=1569400980',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_041.jpg?bwg=1569400977',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_065.jpg?bwg=1569400977',
    },
    youtubeId: '8ykEy-yPBFc',
  },
  {
    name: 'The Iron Giant',
    description: 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.',
    cast: ['Eli Marienthal', 'Harry Connick Jr.', 'Jennifer Aniston'],
    directors: ['Brad Bird'],
    releaseYear: 1999,
    runtime: '1h 26m',
    tags: ['Action', 'Adventure', 'Comedy', 'Drama', 'Family', 'Sci-Fi'],
    avgUserRating: 0,
    imdbRating: 8.1,
    budget: '70 million USD',
    boxOffice: '23 million USD',
    productionCompany: ['Warner Bros'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTk3MDc0MDE3MV5BMl5BanBnXkFtZTYwMTQ1NDg4._V1_.jpg',
    stills: {
      img1: 'https://iv1.lisimg.com/image/7080369/708full-the-iron-giant-screenshot.jpg',
      img2: 'https://iv1.lisimg.com/image/6002793/650full-the-iron-giant-screenshot.jpg',
      img3: 'https://ilarge.lisimg.com/image/2114020/780full-the-iron-giant-screenshot.jpg',
    },
    youtubeId: 'fq2FZdvQXXg',
    officialSite: 'https://www.warnerbros.co.uk/movies/iron-giant',
  },
  {
    name: 'Up',
    description: '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.',
    cast: ['Edward Asner', 'Jordan Nagai', 'John Ratzenberger'],
    directors: ['Pete Docter', 'Bob Peterson'],
    releaseYear: 2009,
    runtime: '1h 36m',
    tags: ['Adventure', 'Comedy', 'Drama', 'Family'],
    avgUserRating: 0,
    imdbRating: 8.3,
    budget: '175 million USD',
    boxOffice: '735 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_.jpg',
    stills: {
      img1: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-96.jpg',
      img2: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-975.jpg',
      img3: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-3421.jpg',
    },
    youtubeId: 'qas5lWp7_R0',
    officialSite: 'https://www.pixar.com/feature-films/up',
  },
  {
    name: 'Toy Story 3',
    description: 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.',
    cast: ['Tom Hanks', 'Tim Allen', 'Joan Cusack',],
    directors: ['Lee Unkrich'],
    releaseYear: 2010,
    runtime: '1h 43m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Toy'],
    avgUserRating: 0,
    imdbRating: 8.3,
    budget: '200 million USD',
    boxOffice: '1.06 billion USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNWM2YTFkODItNTAyZC00ZGYwLTkwYmMtMDZlODc2MTViYjI4XkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg',
    stills: {
      img1: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470766455887-DFPTVNOXSNWXF9L14WNR/Woody6.jpg?format=1500w',
      img2: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1469576277928-TGALSX56DEX1JBFNAF3G/Andy_08.jpg?format=1500w',
      img3: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1469576484631-BCHY0VAMO88LMVBCV057/Landfill_15.jpg?format=1500w',
    },
    youtubeId: 'aGYxNuodVOU',
    officialSite: 'https://www.pixar.com/feature-films/toy-story-3',
  },
  {
    name: 'Ratatouille',
    description: 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.',
    cast: ['Brad Garrett', 'Lou Romano', 'Patton Oswalt'],
    directors: ['Brad Bird', 'Jan Pinkava'],
    releaseYear: 2007,
    runtime: '1h 51m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy'],
    avgUserRating: 0,
    imdbRating: 8.1,
    budget: '150 million USD',
    boxOffice: '623 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_.jpg',
    stills: {
      img1: 'https://mvcdn.fancaps.net/145952.jpg',
      img2: 'https://mvcdn.fancaps.net/146443.jpg',
      img3: 'https://mvcdn.fancaps.net/146627.jpg',
    },
    youtubeId: 'LrGgU2WXnf8',
    officialSite: 'https://www.pixar.com/feature-films/ratatouille',
  },
  {
    name: 'Rango',
    description: 'Rango is an ordinary chameleon who accidentally winds up in the town of Dirt, a lawless outpost in the Wild West in desperate need of a new sheriff.',
    cast: ['Johnny Depp', 'Isla Fisher', 'Timothy Olyphant'],
    directors: ['Gore Verbinski'],
    releaseYear: 2011,
    runtime: '1h 47m',
    tags: ['Action', 'Adventure', 'Animal', 'Comedy', 'FamilyWestern'],
    avgUserRating: 0,
    imdbRating: 7.2,
    budget: '135 million USD',
    boxOffice: '245 million USD',
    productionCompany: ['Paramount Pictures', 'Nickelodeon Movies', 'Blind Wink Productions'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTc4NjEyODE1OV5BMl5BanBnXkFtZTcwMjYzNTkxNA@@._V1_.jpg',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_054.jpg?bwg=1602241231',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_036.jpg?bwg=1602241230',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_049.jpg?bwg=1602241230',
    },
    youtubeId: 'k-OOfW6wWyQ',
  },
  {
    name: 'Pinocchio',
    description: 'A living puppet, with the help of a cricket as his conscience, must prove himself worthy to become a real boy.',
    cast: ['Mel Blanc', 'Billy Bletcher', 'Don Brodie'],
    directors: ['Norman Ferguson', 'T. Hee', 'Wilfred Jackson'],
    releaseYear: 1940,
    runtime: '1h 28m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Toy', 'Insect'],
    avgUserRating: 0,
    imdbRating: 7.5,
    budget: '2.6 million USD',
    boxOffice: '121 million USD',
    productionCompany: ['Walt Disney Animation Studios'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/f/f0/PinocchioPoster.jpeg',
    stills: {
      img1: 'https://mvcdn.fancaps.net/307149.jpg',
      img2: 'https://mvcdn.fancaps.net/307205.jpg',
      img3: 'https://mvcdn.fancaps.net/307485.jpg',
    },
    youtubeId: 'CGXShg3rqf4',
  },
  {
    name: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    cast: [],
    directors: ['Hayao Miyazaki'],
    releaseYear: 2001,
    runtime: '2h 5m',
    tags: ['Adventure', 'Family', 'Fantasy', 'Mystery'],
    avgUserRating: 0,
    imdbRating: 8.6,
    budget: '19 million USD',
    boxOffice: '355 million USD',
    productionCompany: ['Tokuma Shoten', 'Studio Ghibli', 'Nippon Television Network (NTV)'],
    posterImg: 'https://www.studioghibli.com.au/wp-content/uploads/2017/07/MMT051-pf-clean.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/studio-ghibli/images/3/3b/Spirited_Away_%28019%29.jpg',
      img2: 'https://static.wikia.nocookie.net/studio-ghibli/images/4/47/Spirited_Away_%28096%29.jpg',
      img3: 'https://static.wikia.nocookie.net/studio-ghibli/images/4/40/Chihiro_047.jpg',
    },
    youtubeId: 'ByXuk9QqQkk',
    officialSite: 'https://www.studioghibli.com.au/spiritedaway/',
  }
  {
    name: 'My Neighbour Totoro',
    description: 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.',
    cast: ['Noriko Hidaka', 'Chika Sakamoto', 'Shigesato Itoi'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1988,
    runtime: '1h 26m',
    tags: ['Comedy', 'Family', 'Fantasy'],
    avgUserRating: 0,
    imdbRating: 8.1,
    budget: '3.7 million USD',
    boxOffice: '30 million USD',
    productionCompany: ['Tokuma Japan CommunicationsStudio GhibliNibariki'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/studio-ghibli/images/a/a8/Neighbor-totoro-disneyscreencaps.com-9720.jpg',
      img2: 'https://static.wikia.nocookie.net/studio-ghibli/images/a/a6/Totoro_wallpaper_-_black.jpg',
      img3: 'https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Totoro_001.jpg',
    },
    youtubeId: '92a7Hj0ijLs',
    officialSite: 'https://www.studioghibli.com.au/myneighbortotoro/',
  },
  {
    name: 'Toy Story',
    description: 'A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy\'s bedroom.',
    cast: [],
    directors: ['John Lasseter'],
    releaseYear: 1995,
    runtime: '1h 21m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Toy'],
    avgUserRating: 0,
    imdbRating: 8.3,
    budget: '30 million USD',
    boxOffice: '394 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_.jpg',
    stills: {
      img1: 'https://lumiere-a.akamaihd.net/v1/images/open-uri20150608-27674-1525yhh_74a809df.jpeg',
      img2: 'https://lumiere-a.akamaihd.net/v1/images/gallery_toystory_03jpg_2abbab4f.jpeg',
      img3: 'https://lumiere-a.akamaihd.net/v1/images/gallery_toystory_16_0e2d4ef0.jpeg',
    },
    youtubeId: 'wmiIUN-7qhE',
    officialSite: 'https://toystory.disney.com/toy-story',
  },
  {
    name: 'Toy Story 2',
    description: 'When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property with his roundup gang Jessie, Prospector, and Bullseye.',
    cast: ['Tom Hanks', 'Tim Allen', 'Joan Cusack'],
    directors: ['John Lasseter', 'Ash Brannon', 'Lee Unkrich'],
    releaseYear: 1999,
    runtime: '1h 32m',
    tags: ['Adventure', 'ComedyFamilyFantasyToy'],
    avgUserRating: 0,
    imdbRating: 7.9,
    budget: '90 million USD',
    boxOffice: '497 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/0/00/Toy_Story_2_Poster_1.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/disney/images/c/c9/Toy-story-2-characters-desktop-wallpaper-3840x2400.jpg',
      img2: 'https://static.wikia.nocookie.net/disney/images/9/95/Toy_Story_2_-_Promotional_Image_1.jpg',
      img3: 'https://static.wikia.nocookie.net/disney/images/c/c2/Toy-story2-disneyscreencaps.com-28.jpg',
    },
    youtubeId: 'AvWwvcUuNKs',
    officialSite: 'https://toystory.disney.com/toy-story-2',
  },
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  {
    name: '',
    description: '',
    cast: [],
    directors: [],
    releaseYear: ,
    runtime: '',
    tags: [],
    avgUserRating: 0,
    imdbRating: ,
    budget: ,
    boxOffice: ,
    productionCompany: [],
    posterImg: ,
    stills: {
      img1: ,
      img2: ,
      img3: ,
    },
    youtubeId: ,
    officialSite: ,
  }
  
]

export default { movies, users }
