import bcrypt from 'bcrypt'

// ! Hashing the password
const hashPassword = async (password) => {
  const salt = await bcrypt.genSalt(10)
  const hashedPassword = await bcrypt.hash(password, salt)
  return hashedPassword
}


// ! Default users
const users = { 
  admin: {
    name: 'Admin',
    email: 'admin@admin.com',
    userName: 'admin',
    password: await hashPassword('12345'),
    role: 'admin',
  },
  user: {
    name: 'User',
    email: 'user@email.com',
    userName: 'user',
    password: await hashPassword('12345'),
    role: 'user',
    _id: '0B8F639A9B8FEC5181656136',
  },
}


// ! Default movies
const movies = [
  {
    name: 'The Lion King',
    description:
      'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    directors: ['Rogers Allers', 'Rob Minkoff'],
    releaseYear: 1994,
    runtime: '1h 28m',
    tags: ['Adventure', 'Animal', 'Drama', 'Family', 'Musical'],
    imdbRating: 8.5,
    budget: '45 million USD',
    boxOffice: '$968.5 million',
    productionCompany: 'Walt Disney Pictures',
    posterImg:
      'https://www.movies4kids.co.uk/wp-content/uploads/2011/02/the-lion-king-524fb69e8c273.jpg',
    stills: {
      img1: 'https://allears.net/wp-content/uploads/2020/08/circle-of-life.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTgwMzE4OTE1Nl5BMl5BanBnXkFtZTYwMDUwMTQ3._V1_.jpg',
      img3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-1Oe-4ww-BzSzXdb6cPNugK1xklf7uhlsiA&usqp=CAU',
    },
    youtubeId: 'lFzVJEksoDY',
  },
  {
    name: 'The Lego Movie',
    description: 'An ordinary LEGO construction worker, thought to be the prophesied as "special", is recruited to join a quest to stop an evil tyrant from gluing the LEGO universe into eternal stasis.',
    cast: ['Chris Pratt', 'Will Ferrell', 'Elizabeth Banks'],
    directors: ['Phil Lord', 'Christopher Miller'],
    releaseYear: 2014,
    runtime: '1h 40m',
    tags: ['Action', 'Adventure', 'Fantasy', 'Toy', 'Sci-Fi'],
    imdbRating: 7.7,
    budget: '60 million USD',
    boxOffice: '$468.1 million',
    productionCompany: ['Warner Bros'],
    posterImg: 'https://m.media-amazon.com/images/I/8118cL0uL2L._AC_SY741_.jpg',
    stills: {
      img1: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-21.jpg',
      img2: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-11.jpg',
      img3: 'https://www.shockya.com/news/wp-content/uploads/Lego-Movie-13.jpg',
    },
    youtubeId: 'fZ_JOBCLF-I',
    officialSite: 'https://www.warnerbros.com/movies/lego-movie',
  },
  {
    name: 'Akira',
    description: 'A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.',
    cast: ['Mitsuo Iwata', 'Nozomu Sasaki', 'Mami Koyama'],
    directors: ['Katsushiro Otomo'],
    releaseYear: 1988,
    runtime: '2h 4m',
    tags: ['Action', 'Anime', 'Drama', 'Fantasy', 'Sci-Fi', 'Thriller'],
    imdbRating: 8,
    budget: '¥700 million',
    boxOffice: '49 million USD',
    productionCompany: ['Tokyo Movie Shinsha'],
    posterImg: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/AKIRA_%281988_poster%29.jpg/220px-AKIRA_%281988_poster%29.jpg',
    stills: { 
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_006.jpg?bwg=1569515759',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_046.jpg?bwg=1569515756',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Akira_043.jpg?bwg=1569515756',
    },
    youtubeId: 'nA8KmHC2Z-g',
  },
  {
    name: 'The Incredibles',
    description: 'While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.',
    cast: ['Craig Nelson', 'Samuel L. Jackson', 'Holly Hunter'],
    directors: ['Brad Bird'],
    releaseYear: 2004,
    runtime: '1h 55m',
    tags: ['Action', 'Adventure', 'Family', 'Sci-Fi'],
    imdbRating: 8,
    budget: '92 million USD',
    boxOffice: '631 million USD',
    productionCompany: ['Pixar Animations Studies', 'Walt Disney Pictures'],
    posterImg: 'https://3.bp.blogspot.com/-6pm0yLcFDqs/T-mjxClPnHI/AAAAAAAAHts/nonymvXfX6o/s1600/The+Incredibles+%282004%29+1.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/disney/images/4/47/Incredibles-disneyscreencaps.com-754.jpg',
      img2: 'https://static.wikia.nocookie.net/disney/images/4/49/Incredibles-disneyscreencaps.com-11411.jpg',
      img3: 'https://static.wikia.nocookie.net/disney/images/e/ef/Incredibles-disneyscreencaps.com-11903.jpg',
    },
    youtubeId: 'SOKY7XyOHTA',
    officialSite: 'https://www.pixar.com/feature-films/the-incredibles',
  },
  {
    name: 'Wall-E',
    description: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    cast: ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'],
    directors: ['Andrew Stanton'],
    releaseYear: 2008,
    runtime: '1h 38m',
    tags: ['Adventure', 'Family', 'Sci-Fi'],
    imdbRating: 8.4,
    budget: '180 million USD',
    boxOffice: '521 million USD',
    productionCompany: ['Pixar Animation Studios', 'FortyFour Studios', 'Walt Disney Pictures'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/f/f2/Walleposter.jpg',
    stills: {
      img1: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470764072845-47E0I36XDWT09S5AIN75/Walle11.jpg',
      img2: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470764122740-BZ0LLAHWICB1DU74N9RR/Eve12.jpg?format=1500w',
      img3: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470765942248-4QVAI3OTMZLPDO2KDXZ3/Humans10.jpg?format=1500w',
    },
    youtubeId: '4HaQgnPZ4Lo',
    officialSite: 'https://www.pixar.com/feature-films/walle',
  },
  {
    name: 'Perfect Blue',
    description: 'A pop singer gives up her career to become an actress, but she slowly goes insane when she starts being stalked by an obsessed fan and what seems to be a ghost of her past.',
    cast: ['Junko Iwao', 'Rica Matsumoto', 'Shinpachi Tsuji'],
    directors: ['Satoshi Kon'],
    releaseYear: 1997,
    runtime: '1h 21m',
    tags: ['Anime', 'Crime', 'Drama', 'Mystery', 'Thriller'],
    imdbRating: 8,
    budget: '¥3,000,000',
    boxOffice: '563,130 USD',
    productionCompany: ['Rex Entertainment', 'Kotobuki Seihan Printing', 'Asahi Broadcasting Corporation (ABC)'],
    posterImg: 'https://media-cache.cinematerial.com/p/500x/s1stmj3g/perfect-blue-movie-poster.jpg?v=1456615284',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_002.jpg?bwg=1569600824',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_041.jpg?bwg=1569600821',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Perfect_Blue_059.jpg?bwg=1569600821',
    },
    youtubeId: '4uRakM7gpo4',
  },
  {
    name: 'Grave of the Fireflies',
    description: 'A young boy and his little sister struggle to survive in Japan during World War II',
    cast: ['Tsutomu Tatsumi', 'Ayano Shiraishi', 'Akemi Yamaguchi'],
    directors: ['Isao Takahata'],
    releaseYear: 1988,
    runtime: '1h 29m',
    tags: ['Anime'],
    imdbRating: 8.5,
    budget: '3.7 million USD',
    boxOffice: '516,962 USD',
    productionCompany: ['Studio Ghibli', 'Shinchosha Company'],
    posterImg: 'https://static.wikia.nocookie.net/studio-ghibli/images/6/6d/Grave_of_the_Fireflies_poster.jpg',
    stills: {
      img1: 'https://cdni.fancaps.net/file/fancaps-movieimages/2295865.jpg',
      img2: 'https://cdni.fancaps.net/file/fancaps-movieimages/2295911.jpg',
      img3: 'https://cdni.fancaps.net/file/fancaps-movieimages/2296193.jpg',
    },
    youtubeId: '4vPeTSRd580',
    officialSite: 'https://www.ghibli.jp/works/hotarunohaka/',
  },
  {
    name: 'Nausicaa of the Valley of the Wind',
    description: 'Warrior and pacifist Princess Nausicaä desperately struggles to prevent two warring nations from destroying themselves and their dying planet.',
    cast: ['Sumi Shimamoto', 'Mahito Tsujimura', 'Hisako Kyoda'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1984,
    runtime: '1h 57m',
    tags: ['Anime', 'Adventure', 'Sci-Fi'],
    imdbRating: 8,
    budget: '1 million USD',
    boxOffice: '8.8 million USD',
    productionCompany: ['Production companies', 'NibarikiTokuma', 'ShotenHakuhodo'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BZTI3NmJmYTQtNDg4NS00M2VlLTgzZDAtZWIwZDcyOWY5YzIzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY1200_CR85,0,630,1200_AL_.jpg',
    stills: {
      img1: 'https://film-grab.com/2020/03/24/nausicaa-of-the-valley-of-the-wind/#bwg2197/137160',
      img2: 'https://film-grab.com/2020/03/24/nausicaa-of-the-valley-of-the-wind/#bwg2197/137143',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Nausica_065.jpg?bwg=1569499346',
    },
    youtubeId: '6zhLBe319KE',
  },
  {
    name: 'Ghost in the Shell',
    description: 'A cyborg policewoman and her partner hunt a mysterious and powerful hacker called the Puppet Master.',
    cast: ['Atsuko Tanaka', 'Iemasa Kayumi', 'Akio Ôtsuka'],
    directors: ['Mamoru Oshii'],
    releaseYear: 1995,
    runtime: '1h 23m',
    tags: ['Action', 'Anime', 'Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    imdbRating: 7.9,
    budget: '¥330,000,000',
    boxOffice: '918,738 USD',
    productionCompany: ['KôdanshaBandai', 'Visual Company', 'Manga Entertainment'],
    posterImg: 'https://www.scifi-movies.com/images/contenu/data/0000986/affiche-ghost-in-the-shell-1995-3.jpg',
    stills: {
      img1: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506035.jpg',
      img2: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506105.jpg',
      img3: 'https://cdni.fancaps.net/file/fancaps-movieimages/2506429.jpg',
    },
    youtubeId: '8RF09G8Ymqg',
  },
  {
    name: 'Fantastic Mr. Fox',
    description: 'Devil-may-care Mr. Fox quits chicken thieving to start a family with Mrs. Fox, but twelve years later, he leaves his columnist job to rob poultry from three mean farmers who devise a plan to trap Fox and others in the burrowing animal community. With his friends and neighbors, Fox saves his animal community and beats the farmers at their own game.',
    cast: ['George Clooney','Meryl Streep', 'Bill Murray'],
    directors: ['Wes Anderson'],
    releaseYear: 2009,
    runtime: '1h 27m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Crime', 'Drama', 'Family'],
    imdbRating: 7.9,
    budget: '40 million USD',
    boxOffice: '46 million USD',
    productionCompany: ['Twentieth Century Fox', 'Indian Paintbrush', 'New Regency Productions'],
    posterImg: 'https://lumiere-a.akamaihd.net/v1/images/image_3cdae9ca.jpeg',
    stills: {
      img1: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51846',
      img2: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51813',
      img3: 'https://film-grab.com/2013/04/29/fantastic-mr-fox/#bwg841/51830',
    },
    youtubeId: 'n2igjYFojUo',
    officialSite: 'https://family.20thcenturystudios.com/movies/fantastic-mr-fox',
  },
  {
    name: 'Princess Mononoke',
    description: 'While protecting his village from a rampaging boar-god, the young warrior Ashitaka becomes afflicted with a deadly curse. To find the cure that will save his life, he journeys deep into sacred depths of the Great Forest Spirit\'s realm where he meets San (Princess Mononoke), a girl raised by wolves. It\'s not long before Ashitaka is caught in the middle of a battle between iron-ore prospecting humans and the forest dwellers. He must summon the spirit-powers and all his courage to stop man and nature from destroying each other.',
    cast: ['Yôji Matsuda', 'Yuriko Ishida', 'Yûko Tanaka'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1997,
    runtime: '2h 14m',
    tags: ['Anime', 'Adventure', 'Fantasy'],
    imdbRating: 8.4,
    budget: '¥2,400,000,000',
    boxOffice: '170 million USD',
    productionCompany: ['DENTSU Music And Entertainment', 'Nibariki', 'Nippon Television Network (NTV)'],
    posterImg: 'https://static.wikia.nocookie.net/studio-ghibli/images/c/c6/Princess_Mononoke.jpg',
    stills: {
      img1: 'https://film-grab.com/2020/04/20/princess-mononoke/#bwg2305/143290',
      img2: 'https://film-grab.com/2020/04/20/princess-mononoke/#bwg2305/143270',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Princess_Mononoke_055.jpg?bwg=1569601131',
    },
    youtubeId: '4OiMOHRDs14',
  },
  {
    name: 'Zootopia',
    description: 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    cast: ['Ginnifer Goodwin', 'Jason Bateman', 'Idris Elba'],
    directors: ['Byron Howard', 'Rich Moore', 'Jared Bush'],
    releaseYear: 2016,
    runtime: '1h 48m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Crime', 'Family', 'Mystery'],
    imdbRating: 8,
    budget: '150 million USD',
    boxOffice: '1 billion USD',
    productionCompany: ['Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_.jpg',
    stills: {
      img1: 'https://s.movieinsider.com/images/p/274366_m1448424117.jpg',
      img2: 'https://images.fandango.com/r1.0.1039/ImageRenderer/1040/650/redesign/areas/movie/moviesubpages/img/noimage_900x900.jpg/183935/images/masterrepository/fandango/183935/zootopia-ps-11.jpg',
      img3: 'https://s.movieinsider.com/images/p/274368_m1448424186.jpg',
    },
    youtubeId: 'jWM0ct-OLsM',
    officialSite: 'https://disneyanimation.com/films/zootopia/',
  },
  {
    name: 'Paprika',
    description: 'When a machine that allows therapists to enter their patients\' dreams is stolen, all hell breaks loose. Only a young female therapist, Paprika, can stop it.',
    cast: ['Megumi Hayashibara', 'Tôru Emori', 'Katsunosuke Hori'],
    directors: ['Satoshi Kon'],
    releaseYear: 2006,
    runtime: '1h 30m',
    tags: ['Drama', 'Fantasy', 'Mystery', 'Sci-Fi', 'Thriller'],
    imdbRating: 7.7,
    budget: '¥300,000,000',
    boxOffice: '946,590 million USD',
    productionCompany: ['Madhouse', 'Sony Pictures Entertainment'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNDI4MGEwZDAtZDg0Yy00MjFhLTg1MjctODdmZTMyNTUyNDI3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
    stills: {
      img1: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-134.jpg',
      img2: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-011.jpg',
      img3: 'https://screenmusings.org/movie/blu-ray/Paprika/images/Paprika-002.jpg',
    },
    youtubeId: 'PIUqozzyW2k',
    officialSite: 'https://www.sonypictures.com/movies/paprika',
  },
  {
    name: 'Waltz with Bashir',
    description: 'An Israeli film director interviews fellow veterans of the 1982 invasion of Lebanon to reconstruct his own memories of his term of service in that conflict.',
    cast: ['Ari Folman', 'Ron Ben-Yishai', 'Ronny Dayag'],
    directors: ['Ari Folman'],
    releaseYear: 2008,
    runtime: '1h 30m',
    tags: ['Documentary', 'Biography', 'Drama', 'History', 'Mystery', 'War'],
    imdbRating: 8,
    budget: '1.5 million USD',
    boxOffice: '11 million USD',
    productionCompany: ['Bridgit Folman Film Gang', 'Les Films d\'Ici', 'Razor Film Produktion GmbH'],
    posterImg: 'https://cdn.posteritati.com/posters/000/000/027/594/waltz-with-bashir-md-web.jpg',
    stills: {
      img1: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-11.jpg',
      img2: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-3.jpg',
      img3: 'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/118670/waltzwithbashir-mv-7.jpg',
    },
    youtubeId: 'XbXdwBNkCmk',
    officialSite: 'https://www.sonypictures.com/movies/waltzwithbashir',
  },
  {
    name: 'Laputa: Castle in the Sky',
    description: 'A young boy and a girl with a magic crystal must race against pirates and foreign agents in a search for a legendary floating castle.',
    cast: ['Mayumi Tanaka', 'Keiko Yokozawa', 'Kotoe Hatsui'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1986,
    runtime: '2h 5m',
    tags: ['Anime', 'Adventure', 'Family', 'Fantasy'],
    imdbRating: 8,
    budget: '3.3 million USD',
    boxOffice: '6.1 million USD',
    productionCompany: ['Tokuma Shoten', 'Studio Ghibli'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNDFhZmY2NTgtMzljYy00MTlhLTgyMjItNTEwZWJkYThhYzkyXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_.jpg',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_002.jpg?bwg=1569400980',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_041.jpg?bwg=1569400977',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Castle_in_the_Sky_065.jpg?bwg=1569400977',
    },
    youtubeId: '8ykEy-yPBFc',
  },
  {
    name: 'The Iron Giant',
    description: 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.',
    cast: ['Eli Marienthal', 'Harry Connick Jr.', 'Jennifer Aniston'],
    directors: ['Brad Bird'],
    releaseYear: 1999,
    runtime: '1h 26m',
    tags: ['Action', 'Adventure', 'Comedy', 'Drama', 'Family', 'Sci-Fi'],
    imdbRating: 8.1,
    budget: '70 million USD',
    boxOffice: '23 million USD',
    productionCompany: ['Warner Bros'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTk3MDc0MDE3MV5BMl5BanBnXkFtZTYwMTQ1NDg4._V1_.jpg',
    stills: {
      img1: 'https://iv1.lisimg.com/image/7080369/708full-the-iron-giant-screenshot.jpg',
      img2: 'https://iv1.lisimg.com/image/6002793/650full-the-iron-giant-screenshot.jpg',
      img3: 'https://ilarge.lisimg.com/image/2114020/780full-the-iron-giant-screenshot.jpg',
    },
    youtubeId: 'fq2FZdvQXXg',
    officialSite: 'https://www.warnerbros.co.uk/movies/iron-giant',
  },
  {
    name: 'Up',
    description: '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.',
    cast: ['Edward Asner', 'Jordan Nagai', 'John Ratzenberger'],
    directors: ['Pete Docter', 'Bob Peterson'],
    releaseYear: 2009,
    runtime: '1h 36m',
    tags: ['Adventure', 'Comedy', 'Drama', 'Family'],
    imdbRating: 8.3,
    budget: '175 million USD',
    boxOffice: '735 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_.jpg',
    stills: {
      img1: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-96.jpg',
      img2: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-975.jpg',
      img3: 'https://i0.wp.com/caps.pictures/200/9-up/full/up-disneyscreencaps.com-3421.jpg',
    },
    youtubeId: 'qas5lWp7_R0',
    officialSite: 'https://www.pixar.com/feature-films/up',
  },
  {
    name: 'Toy Story 3',
    description: 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.',
    cast: ['Tom Hanks', 'Tim Allen', 'Joan Cusack'],
    directors: ['Lee Unkrich'],
    releaseYear: 2010,
    runtime: '1h 43m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Toy'],
    imdbRating: 8.3,
    budget: '200 million USD',
    boxOffice: '1.06 billion USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNWM2YTFkODItNTAyZC00ZGYwLTkwYmMtMDZlODc2MTViYjI4XkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg',
    stills: {
      img1: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1470766455887-DFPTVNOXSNWXF9L14WNR/Woody6.jpg',
      img2: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1469576277928-TGALSX56DEX1JBFNAF3G/Andy_08.jpg',
      img3: 'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1469576484631-BCHY0VAMO88LMVBCV057/Landfill_15.jpg',
    },
    youtubeId: 'aGYxNuodVOU',
    officialSite: 'https://www.pixar.com/feature-films/toy-story-3',
  },
  {
    name: 'Ratatouille',
    description: 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.',
    cast: ['Brad Garrett', 'Lou Romano', 'Patton Oswalt'],
    directors: ['Brad Bird', 'Jan Pinkava'],
    releaseYear: 2007,
    runtime: '1h 51m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy'],
    imdbRating: 8.1,
    budget: '150 million USD',
    boxOffice: '623 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_.jpg',
    stills: {
      img1: 'https://mvcdn.fancaps.net/145952.jpg',
      img2: 'https://mvcdn.fancaps.net/146443.jpg',
      img3: 'https://mvcdn.fancaps.net/146627.jpg',
    },
    youtubeId: 'LrGgU2WXnf8',
    officialSite: 'https://www.pixar.com/feature-films/ratatouille',
  },
  {
    name: 'Rango',
    description: 'Rango is an ordinary chameleon who accidentally winds up in the town of Dirt, a lawless outpost in the Wild West in desperate need of a new sheriff.',
    cast: ['Johnny Depp', 'Isla Fisher', 'Timothy Olyphant'],
    directors: ['Gore Verbinski'],
    releaseYear: 2011,
    runtime: '1h 47m',
    tags: ['Action', 'Adventure', 'Animal', 'Comedy', 'FamilyWestern'],
    imdbRating: 7.2,
    budget: '135 million USD',
    boxOffice: '245 million USD',
    productionCompany: ['Paramount Pictures', 'Nickelodeon Movies', 'Blind Wink Productions'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTc4NjEyODE1OV5BMl5BanBnXkFtZTcwMjYzNTkxNA@@._V1_.jpg',
    stills: {
      img1: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_054.jpg?bwg=1602241231',
      img2: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_036.jpg?bwg=1602241230',
      img3: 'https://film-grab.com/wp-content/uploads/photo-gallery/Rango_049.jpg?bwg=1602241230',
    },
    youtubeId: 'k-OOfW6wWyQ',
  },
  {
    name: 'Pinocchio',
    description: 'A living puppet, with the help of a cricket as his conscience, must prove himself worthy to become a real boy.',
    cast: ['Mel Blanc', 'Billy Bletcher', 'Don Brodie'],
    directors: ['Norman Ferguson', 'T. Hee', 'Wilfred Jackson'],
    releaseYear: 1940,
    runtime: '1h 28m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Toy', 'Insect'],
    imdbRating: 7.5,
    budget: '2.6 million USD',
    boxOffice: '121 million USD',
    productionCompany: ['Walt Disney Animation Studios'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/f/f0/PinocchioPoster.jpeg',
    stills: {
      img1: 'https://mvcdn.fancaps.net/307149.jpg',
      img2: 'https://mvcdn.fancaps.net/307205.jpg',
      img3: 'https://mvcdn.fancaps.net/307485.jpg',
    },
    youtubeId: 'CGXShg3rqf4',
  },
  {
    name: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    cast: [],
    directors: ['Hayao Miyazaki'],
    releaseYear: 2001,
    runtime: '2h 5m',
    tags: ['Adventure', 'Family', 'Fantasy', 'Mystery'],
    imdbRating: 8.6,
    budget: '19 million USD',
    boxOffice: '355 million USD',
    productionCompany: ['Tokuma Shoten', 'Studio Ghibli', 'Nippon Television Network (NTV)'],
    posterImg: 'https://www.studioghibli.com.au/wp-content/uploads/2017/07/MMT051-pf-clean.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/studio-ghibli/images/3/3b/Spirited_Away_%28019%29.jpg',
      img2: 'https://static.wikia.nocookie.net/studio-ghibli/images/4/47/Spirited_Away_%28096%29.jpg',
      img3: 'https://static.wikia.nocookie.net/studio-ghibli/images/4/40/Chihiro_047.jpg',
    },
    youtubeId: 'ByXuk9QqQkk',
    officialSite: 'https://www.studioghibli.com.au/spiritedaway/',
  },
  {
    name: 'My Neighbour Totoro',
    description: 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.',
    cast: ['Noriko Hidaka', 'Chika Sakamoto', 'Shigesato Itoi'],
    directors: ['Hayao Miyazaki'],
    releaseYear: 1988,
    runtime: '1h 26m',
    tags: ['Comedy', 'Family', 'Fantasy'],
    imdbRating: 8.1,
    budget: '3.7 million USD',
    boxOffice: '30 million USD',
    productionCompany: ['Tokuma Japan CommunicationsStudio GhibliNibariki'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/studio-ghibli/images/a/a8/Neighbor-totoro-disneyscreencaps.com-9720.jpg',
      img2: 'https://static.wikia.nocookie.net/studio-ghibli/images/a/a6/Totoro_wallpaper_-_black.jpg',
      img3: 'https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Totoro_001.jpg',
    },
    youtubeId: '92a7Hj0ijLs',
    officialSite: 'https://www.studioghibli.com.au/myneighbortotoro/',
  },
  {
    name: 'Toy Story',
    description: 'A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy\'s bedroom.',
    cast: [],
    directors: ['John Lasseter'],
    releaseYear: 1995,
    runtime: '1h 21m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Toy'],
    imdbRating: 8.3,
    budget: '30 million USD',
    boxOffice: '394 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_.jpg',
    stills: {
      img1: 'https://lumiere-a.akamaihd.net/v1/images/open-uri20150608-27674-1525yhh_74a809df.jpeg',
      img2: 'https://lumiere-a.akamaihd.net/v1/images/gallery_toystory_03jpg_2abbab4f.jpeg',
      img3: 'https://lumiere-a.akamaihd.net/v1/images/gallery_toystory_16_0e2d4ef0.jpeg',
    },
    youtubeId: 'wmiIUN-7qhE',
    officialSite: 'https://toystory.disney.com/toy-story',
  },
  {
    name: 'Toy Story 2',
    description: 'When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property with his roundup gang Jessie, Prospector, and Bullseye.',
    cast: ['Tom Hanks', 'Tim Allen', 'Joan Cusack'],
    directors: ['John Lasseter', 'Ash Brannon', 'Lee Unkrich'],
    releaseYear: 1999,
    runtime: '1h 32m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Toy'],
    imdbRating: 7.9,
    budget: '90 million USD',
    boxOffice: '497 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/0/00/Toy_Story_2_Poster_1.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/disney/images/c/c9/Toy-story-2-characters-desktop-wallpaper-3840x2400.jpg',
      img2: 'https://static.wikia.nocookie.net/disney/images/9/95/Toy_Story_2_-_Promotional_Image_1.jpg',
      img3: 'https://static.wikia.nocookie.net/disney/images/c/c2/Toy-story2-disneyscreencaps.com-28.jpg',
    },
    youtubeId: 'AvWwvcUuNKs',
    officialSite: 'https://toystory.disney.com/toy-story-2',
  },
  {
    name: 'Finding Nemo',
    description: 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.',
    cast: ['Albert Brooks', 'Ellen DeGeneres', 'Alexander Gould'],
    directors: ['Andrew Stanton', 'Lee Unkrich'],
    releaseYear: 2003,
    runtime: '1h 40m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family'],
    imdbRating: 8.2,
    budget: '94 million USD',
    boxOffice: '940 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://static.wikia.nocookie.net/disney/images/b/ba/Finding_Nemo-_2003.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/pixar/images/f/f8/Findet_nemo_vater_sohn.jpg',
      img2: 'https://static.wikia.nocookie.net/pixar/images/3/33/Findet_nemo_hai.jpg',
      img3: 'https://static.wikia.nocookie.net/pixar/images/2/26/Finding-nemo-dory-marlin.jpg',
    },
    youtubeId: '2zLkasScy7A',
    officialSite: 'https://www.pixar.com/feature-films/finding-nemo',
  },
  {
    name: 'Fantasia',
    description: 'A collection of animated interpretations of great works of Western classical music, ranging from the abstract to depictions of mythology and fantasy, and settings including the prehistoric, supernatural and sacred.',
    cast: ['Leopold Stokowski', 'Deems Taylor', 'The Philadelphia Orchestra'],
    directors: ['James Algar', 'Samuel Armstrong'],
    releaseYear: 1940,
    runtime: '2h 5m',
    tags: ['Animal', 'Family', 'Fantasy', 'Musical'],
    imdbRating: 7.7,
    budget: '2.2 million USD',
    boxOffice: '76 million USD',
    productionCompany: ['Walt Disney Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMjAxMTI1Njk3OF5BMl5BanBnXkFtZTgwNjkzODk4NTE@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMzMzMTg5NDEwOF5BMl5BanBnXkFtZTcwODUyOTAyNw@@._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTM2OTk4NTIyNl5BMl5BanBnXkFtZTcwMTYyOTAyNw@@._V1_.jpg',
      img3: 'https://www.cornel1801.com/disney/Fantasia-1940/film6_3.jpg',
    },
    youtubeId: 'Q4S92yRzJa8',
  },
  {
    name: 'Snow White and the Seven Dwarfs',
    description: 'Exiled into the dangerous forest by her wicked stepmother, a princess is rescued by seven dwarf miners who make her part of their household.',
    cast: ['Adriana Caselotti', 'Harry Stockwell', 'Lucille La Verne'],
    directors: ['William Cottrell', 'David Hand', 'Wilfred Jackson'],
    releaseYear: 1937,
    runtime: '1h 23m',
    tags: ['Adventure', 'Family', 'Fantasy', 'Musical', 'Romance'],
    imdbRating: 7.6,
    budget: '1.4 millions USD',
    boxOffice: '184 million USD',
    productionCompany: [],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMTM2OTA3NjUwNV5BMl5BanBnXkFtZTcwOTc0MjY2Nw@@._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTk1NjI0ODk4MF5BMl5BanBnXkFtZTcwMDk5NDIyNw@@._V1_.jpg',
      img3: 'https://eu-images.contentstack.com/v3/assets/blt8bbf16c2d7a209e5/bltbf97d8af6b601c1e/61f1023dd2574055e1a5a6c7/sw.jpg',
    },
    youtubeId: 'WKSd9-12cj4',
  },
  {
    name: 'Monsters, Inc',
    description: 'In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.',
    cast: ['Billy Crystal', 'John Goodman', 'Mary Gibbs'],
    directors: ['Pete Docter', 'David Silverman', 'Lee Unkrich'],
    releaseYear: 2001,
    runtime: '1h 23m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy'],
    imdbRating: 8.1,
    budget: '115 million USD',
    boxOffice: '579 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMTUxNzQwNTQ0N15BMl5BanBnXkFtZTYwMDg5NzA3._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTYxNzc1ODk4NF5BMl5BanBnXkFtZTcwNzQ4MDIyNw@@._V1_.jpg',
      img3: 'https://i.redd.it/9rjl6clizmh51.jpg',
    },
    youtubeId: 'cvOQeozL4S0',
    officialSite: 'https://www.pixar.com/feature-films/monsters-inc',
  },
  {
    name: 'Beauty and the Beast',
    description: 'A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman\'s love.',
    cast: ['Paige O\'Hara', 'Robby Benson', 'Jesse Corti'],
    directors: ['Gary Trousdale', 'Kirk Wise'],
    releaseYear: 1991,
    runtime: '1h 24m',
    tags: ['Family', 'Fantasy', 'Musical', 'Romance'],
    imdbRating: 8,
    budget: '25 million USD',
    boxOffice: '424 million USD',
    productionCompany: [],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMzE5MDM1NDktY2I0OC00YWI5LTk2NzUtYjczNDczOWQxYjM0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://i.insider.com/565e082cc281441d008b6861?width=700',
      img2: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/03/Print-Issue-10-fea_beautyandthebeast-Potts-Everett-MSDBEAN_WD006-EMBED-2022.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BOTA2MjU2MDkxOV5BMl5BanBnXkFtZTgwOTE2ODMzMzE@._V1_QL75_UX500_CR0,0,500,281_.jpg',
    },
    youtubeId: '6StqkSdOsKE',
  },
  {
    name: 'The Nightmare Before Christmas',
    description: 'Jack Skellington, king of Halloween Town, discovers Christmas Town, but his attempts to bring Christmas to his home causes confusion.',
    cast: ['Danny Elfman', 'Chris Sarandon', 'Catherine O\'Hara'],
    directors: [' Henry Selick'],
    releaseYear: 2014,
    runtime: '1h 16m',
    tags: ['FamilyFantasyMusical'],
    imdbRating: 7.9,
    budget: '18 million USD',
    boxOffice: '91 million USD',
    productionCompany: ['Touchstone Pictures', 'Skellington Productions Inc.', 'Tim Burton Productions'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://i.pinimg.com/originals/a1/19/04/a1190422ac4642eaa9772672fad338e3.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTQxNTY0NDE2Nl5BMl5BanBnXkFtZTcwMzg2ODMyMw@@._V1_.jpg',
      img3: 'https://i.pinimg.com/originals/79/c7/84/79c784a1d8c98fde0aefb91208392bc3.jpg',
    },
    youtubeId: 'wr6N_hZyBCk',
  },
  {
    name: 'The Little Mermaid',
    description: 'A mermaid princess makes a Faustian bargain in an attempt to become human and win a prince\'s love.',
    cast: [' Jodi Benson, Samuel E. Wright, Rene Auberjonois,'],
    directors: ['Ron Clements, John Musker '],
    releaseYear: 2014,
    runtime: '1h 23m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Romance'],
    imdbRating: 7.6,
    budget: '40 million USD',
    boxOffice: '211 million USD',
    productionCompany: ['Walt Disney PicturesSilver Screen Partners IVWalt Disney Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNWNhNjA1ZWItMmYyOS00NDRlLThiZDItYjBmMmRjZjgyMDBlXkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMTcxNDM3OTMzOV5BMl5BanBnXkFtZTcwODYxMDIyNw@@._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTQwNjQ5MTY0NF5BMl5BanBnXkFtZTcwOTcxMDIyNw@@._V1_.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BMjI0MzEyMDU2MV5BMl5BanBnXkFtZTcwODcxMDIyNw@@._V1_.jpg',
    },
    youtubeId: 'ZGZX5-PAwR8',
  },
  {
    name: 'Aladdin',
    description: 'A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.',
    cast: [' Scott Weinger, Robin Williams, Linda Larkin'],
    directors: ['Ron Clements, John Musker'],
    releaseYear: 1992,
    runtime: '1h 30m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Romance'],
    imdbRating: 8,
    budget: '28 million USD',
    boxOffice: '504 million USD',
    productionCompany: ['Walt Disney PicturesSilver Screen Partners IVWalt Disney Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNTA1YzE1MmYtMzI1ZC00YTcwLTliZGYtMzIyODZlMWQxYWI4XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMjI4MDAzODYwOF5BMl5BanBnXkFtZTcwMTIzODAyNw@@._V1_.jpg',
      img2: 'https://media.glamour.com/photos/56958053085ae0a85036fa95/master/pass/entertainment-2015-04-aladdin-live-action-main.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BOTgyMzY5NTYxN15BMl5BanBnXkFtZTcwMzIzODAyNw@@._V1_.jpg',
    },
    youtubeId: 'eTjHiQKJUDY',
  },
  {
    name: 'How to Train Your Dragon',
    description: 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.',
    cast: ['Jay Baruchel', 'Gerard Butler', 'Christopher Mintz-Plasse'],
    directors: ['Dean DeBlois, Chris Sanders'],
    releaseYear: 2010,
    runtime: '1h 38m',
    tags: ['ActionAdventureAnimalComedyFamilyFantasy'],
    imdbRating: 8.1,
    budget: '165 million USD',
    boxOffice: '494 million USD',
    productionCompany: ['DreamWorks AnimationMad Hatter EntertainmentVertigo Entertainment'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://static.wikia.nocookie.net/dreamworks/images/3/38/Toothless..jpeg',
      img2: 'https://static.wikia.nocookie.net/dreamworks/images/2/24/How-to-train-disneyscreencaps_com-4349.jpg',
      img3: 'https://static.wikia.nocookie.net/dreamworks/images/6/63/How-to-train-disneyscreencaps_com-7649.jpg',
    },
    youtubeId: 'GfBHLVtbG6U',
  },
  {
    name: 'Bambi',
    description: 'The story of a young deer growing up in the forest',
    cast: ['Hardie Albright, Stan Alexander, Bobette Audrey'],
    directors: ['James Algar, Samuel Armstrong'],
    releaseYear: 1942,  
    runtime: '1h 9m',
    tags: ['Adventure', 'Animal', 'Drama', 'Family'],
    imdbRating: 7.3,
    budget: '102 million USD',
    boxOffice: '267 million USD',
    productionCompany: ['Walt Disney Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BY2JhMTJmYjYtNTVkYi00OWE3LWJlMjEtOWI4MTFkMjJhMmQ3XkEyXkFqcGdeQXVyNzY1NDgwNjQ@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BOTQyODY3ODEyNV5BMl5BanBnXkFtZTcwNzIxNjg1NA@@._V1_.jpg',
      img2: 'https://static.dw.com/image/39996297_303.jpg',
      img3: 'https://static.independent.co.uk/s3fs-public/thumbnails/image/2019/10/30/16/bambi.png',
    },
    youtubeId: 'yDGv4GIR7A4',
  },
  {
    name: 'Wallace and Gromit: The Curse of the Were-Rabbit',
    description: 'Wallace and his loyal dog, Gromit, set out to discover the mystery behind the garden sabotage that plagues their village and threatens the annual giant vegetable growing contest.',
    cast: [' Peter Sallis, Helena Bonham Carter, Ralph Fiennes,'],
    directors: [' Steve Box, Nick Park'],
    releaseYear: 2005,
    runtime: '1h 25m',
    tags: ['AdventureAnimalComedyFamilyFantasyMysterySci-Fi'],
    imdbRating: 7.5,
    budget: '30 million USD',
    boxOffice: '194 million USD',
    productionCompany: ['Aardman AnimationsDreamWorks Animation'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BZmExY2Y3NGQtMzg5ZC00MGY1LTk3ZjktNWYyYzYwMTA1MTUwXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BNzIwMjYxNTA5Ml5BMl5BanBnXkFtZTcwOTU1NzkyMw@@._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BODY2NDcyMjM3N15BMl5BanBnXkFtZTcwMDQ1NzkyMw@@._V1_.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BMTk4NjI1OTE5MV5BMl5BanBnXkFtZTcwNzY1NzkyMw@@._V1_.jpg',
    },
    youtubeId: '-08b_XI60_4',
  },
  {
    name: 'Shrek',
    description: 'A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.',
    cast: ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz'],
    directors: ['Andrew Adamson', 'Vicky Jenson'],
    releaseYear: 2001,
    runtime: '1h 30m',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy', 'Romance'],
    imdbRating: 7.9,
    budget: '60 million USD',
    boxOffice: '488 millon USD',
    productionCompany: ['DreamWorks Animation', 'Dreamworks Pictures', 'Pacific Data Images (PDI)'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMTAyODc3Njc1NjdeQTJeQWpwZ15BbWU3MDQ3MDgyNDY@._V1_.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTczNjE0MDQ3NF5BMl5BanBnXkFtZTcwOTYzNDc3Mw@@._V1_.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BMTkyODcyMTg0Ml5BMl5BanBnXkFtZTcwMTgwODI0Ng@@._V1_.jpg',
    },
    youtubeId: 'CwXOrWvPBPk',
  },
  {
    name: 'Coraline',
    description: 'An adventurous 11-year-old girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.',
    cast: [' Dakota Fanning, Teri Hatcher, John Hodgman,'],
    directors: ['Henry Selick'],
    releaseYear: 2009,
    runtime: '1h 40m',
    tags: ['Drama', 'Insects', 'Family', 'Fantasy', 'Thriller'],
    imdbRating: 7.7,
    budget: '60 million USD',
    boxOffice: '124 million USD',
    productionCompany: ['Focus FeaturesLaika EntertainmentPandemonium'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMzQxNjM5NzkxNV5BMl5BanBnXkFtZTcwMzg5NDMwMg@@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://i.pinimg.com/originals/4d/68/43/4d6843ee381187c333168e8317c7955f.jpg',
      img2: 'https://m.media-amazon.com/images/M/MV5BMTA0NzcyMDkwOTJeQTJeQWpwZ15BbWU3MDgxNjEwMzI@._V1_.jpg',
      img3: 'https://media.timeout.com/images/101527285/image.jpg',
    },
    youtubeId: 'm9bOpeuvNwY',
  },
  {
    name: 'Frozen',
    description: 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.',
    cast: [' Kristen Bell', 'Idina Menzel', 'Jonathan Groff'],
    directors: ['Chris Buck', 'Jennifer Lee'],
    releaseYear: 2013,
    runtime: '1h 42,',
    tags: ['Adventure', 'Animal', 'Comedy', 'Family', 'Fantasy', 'Musical'],
    imdbRating: 7.4,
    budget: '150 million USD',
    boxOffice: '1.2 billion USD',
    productionCompany: ['Walt Disney Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNzE1OTkwOTkwMV5BMl5BanBnXkFtZTgwNTcwMDk4NTE@._V1_.jpg',
    stills: {
      img1: 'https://lumiere-a.akamaihd.net/v1/images/open-uri20150608-27674-1k1ybhv_28ad7d5d.jpeg',
      img2: 'https://lumiere-a.akamaihd.net/v1/images/open-uri20150608-27674-1i27pow_fa818fbc.jpeg',
      img3: 'https://lumiere-a.akamaihd.net/v1/images/open-uri20150608-27674-1b62cco_adb79689.jpeg',
    },
    youtubeId: 'TbQm5doF_Uc',
  },
  {
    name: 'Your Name.',
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    cast: ['Ryûnosuke Kamiki', 'Mone Kamishiraishi', 'Ryô Narita'],
    directors: ['Makoto Shinkai'],
    releaseYear: 2016,
    runtime: '1h 46m',
    tags: ['Anime', 'Drama', 'Fantasy', 'Romance'],
    imdbRating: 8.4,
    budget: '¥370,000,000',
    boxOffice: '358 million USD',
    productionCompany: ['AmuseCoMix Wave Films', 'East Japan Marketing & Communications Inc.'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_QL75_UX190_CR0,0,190,281_.jpg',
    stills: {
      img1: 'https://screenmusings.org/movie/blu-ray/Your-Name/images/Your-Name-047.jpg',
      img2: 'https://screenmusings.org/movie/blu-ray/Your-Name/images/Your-Name-055.jpg',
      img3: 'https://screenmusings.org/movie/blu-ray/Your-Name/images/Your-Name-058.jpg',
    },
    youtubeId: 's0wTdCQoc2k',
  },
  {
    name: 'Coco',
    description: 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
    cast: [' Anthony Gonzalez, Gael García Bernal, Benjamin Bratt'],
    directors: [' Lee Unkrich, Adrian Molina'],
    releaseYear: 2017,
    runtime: '1h 45m',
    tags: ['AdventureComedyFamilyFantasyMusicMystery'],
    imdbRating: 8.4,
    budget: '175 million USD',
    boxOffice: '807 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg',
    stills: {
      img1: 'https://www.indiewire.com/wp-content/uploads/2017/08/coco586c323777b11-e1510248506244.jpg',
      img2: 'https://wallpaperaccess.com/full/1334568.jpg',
      img3: 'https://lumiere-a.akamaihd.net/v1/images/eu_coco_7things_gl_1_r_9d49785c.jpeg',
    },
    youtubeId: 'Ga6RYejo6Hk',
  },
  {
    name: 'Bob\'s Burgers: The Movie',
    description: 'The Belchers try to save the restaurant from closing as a sinkhole forms in front of it, while the kids try to solve a mystery that could save their family\'s restaurant.',
    cast: ['H. Jon Benjamin', 'Kristen Schaal', 'Dan Mintz'],
    directors: [' Loren Bouchard', 'Bernard Derriman'],
    releaseYear: 2022,
    runtime: '1h 42m',
    tags: ['AdventureComedyMusical'],
    imdbRating: 7,
    budget: '38 million USD',
    boxOffice: '34 million USD',
    productionCompany: ['20th Century Studios', 'Fox Animation Studios', 'Buck & Millie Productions'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMWQyYjU1ZTAtNjhlMy00NGE3LWI2YTgtM2E0MDk0ZTIwNGE5XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg',
    stills: {
      img1: 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.WqA8~2eefa/w:600/h:251/q:75/https://bleedingcool.com/wp-content/uploads/2022/01/01.00.31.02_bobs_burgers_bt1886.jpg',
      img2: 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.WqA8~2eefa/w:600/h:251/q:75/https://bleedingcool.com/wp-content/uploads/2022/01/01.01.03.22_bobs_burgers_bt1886.jpg',
      img3: 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.WqA8~2eefa/w:600/h:251/q:75/https://bleedingcool.com/wp-content/uploads/2022/01/01.00.51.13_bobs_burgers_bt1886.jpg',
    },
    youtubeId: 'hbGXqUumtqg',
  },
  {
    name: 'Luca',
    description: 'On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.',
    cast: [' Jacob Tremblay', 'Jack Dylan Grazer', 'Emma Berman'],
    directors: ['Enrico Casarosa'],
    releaseYear: 2021,
    runtime: '1h 35m',
    tags: ['AdventureComedyFamilyFantasy'],
    imdbRating: 7.4,
    budget: 'n/a',
    boxOffice: '49 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BZTQyNTU0MDktYTFkYi00ZjNhLWE2ODctMzBkM2U1ZTk3YTMzXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://lumiere-a.akamaihd.net/v1/images/bc0247d774173dbcae97e5f3a80e2b58_4096x2214_9cf59b35.jpeg',
      img2: 'https://media.wdwnt.com/2021/06/Luca-8-9316829-1200x675.jpeg',
      img3: 'https://image.cnbcfm.com/api/v1/image/106895922-1623427129562-luca_Cropped.jpg',
    },
    youtubeId: 'mYfJxlgR2jw',
  },
  {
    name: 'Inside Out',
    description: 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.',
    cast: [' Amy Poehler, Bill Hader, Lewis Black'],
    directors: ['Pete Docter', 'Ronnie Del Carmen'],
    releaseYear: 2015,
    runtime: '1h 35m',
    tags: ['AdventureComedyDramaFamilyFantasy'],
    imdbRating: 8.2,
    budget: '175 million USD',
    boxOffice: '858 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://m.media-amazon.com/images/M/MV5BMTQ4MDQwNTU3NF5BMl5BanBnXkFtZTgwNTk3NTE2NTE@._V1_.jpg',
      img2: 'https://www.5minutesformom.com/wp-content/uploads/2014/12/Inside-Out-Still-Image-InsideOut.jpg',
      img3: 'https://pics.filmaffinity.com/Inside_Out-690059628-large.jpg',
    },
    youtubeId: 'seMwpP0yeu4',
  },
  {
    name: 'Space Jam',
    description: 'In a desperate attempt to win a basketball match and earn their freedom, the Looney Tunes seek the aid of retired basketball champion, Michael Jordan.',
    cast: ['Michael Jordan', 'Wayne Knight', 'Theresa Randle'],
    directors: ['Joe Pytka'],
    releaseYear: 1996,
    runtime: '1h 28m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Sci-Fi', 'Sport'],
    imdbRating: 6.5,
    budget: '80 million USD',
    boxOffice: '230 million USD',
    productionCompany: ['Warner Bros. Family EntertainmentNorthern Lights EntertainmentCourtside Seats Productions'],
    posterImg: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/14/Space_jam.jpg/220px-Space_jam.jpg',
    stills: {
      img1: 'https://www.spacejam.com/1996/cmp/jamcentral/img/photos/liveanim7.jpg',
      img2: 'https://a.ltrbxd.com/resized/sm/upload/yg/z7/06/jl/space-jam-1200-1200-675-675-crop-000000.jpg',
      img3: 'https://static.onecms.io/wp-content/uploads/sites/6/1996/11/space-jam-bill-murray.jpg',
    },
    youtubeId: 'oKNy-MWjkcU',
  },
  {
    name: 'Final Fantasy VII: Advent Children',
    description: 'An ex-mercenary is forced out of isolation when three mysterious men kidnap and brainwash the city\'s children afflicted with the Geostigma disease.',
    cast: ['Ayumi Ito', 'Takahiro Sakurai', 'Mena Suvari'],
    directors: ['Tetsuya Nomura'],
    releaseYear: 2005,
    runtime: '1h 41m',
    tags: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
    imdbRating: 7.2,
    budget: 'N/A',
    boxOffice: 'N/A',
    productionCompany: ['Square Enix CompanySquare Enix Image Studio DivisionSquare USA'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNTk4NjBhZTUtN2MwMy00MzIyLWFhN2ItMmUwYzQ4MWQxODM3L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_FMjpg_UX1000_.jpg',
    stills: {
      img1: 'https://sm.ign.com/ign_ap/review/f/final-fant/final-fantasy-vii-advent-children-import-review_6z8j.jpg',
      img2: 'https://ladygeekgirl.files.wordpress.com/2017/03/cloud-advent-children1.jpg',
      img3: 'https://media-cache.cinematerial.com/p/500x/q4lvjg5t/final-fantasy-vii-advent-children-movie-poster.jpg',
    },
    youtubeId: 'wut2am39z-c',
  },
  {
    name: 'Brave',
    description: 'Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.',
    cast: ['Kelly Macdonald, Billy Connolly, Emma Thompson'],
    directors: [' Mark Andrews, Brenda Chapman, Steve Purcell'],
    releaseYear: 2012,
    runtime: '1h 33m',
    tags: ['Adventure', 'Comedy', 'Family', 'Fantasy'],
    imdbRating: 7.1,
    budget: '185 million USD',
    boxOffice: '538 million USD',
    productionCompany: ['Walt Disney Pictures', 'Pixar Animation Studios'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_.jpg',
    stills: {
      img1: 'https://collider.com/wp-content/uploads/brave-movie-image-merida-swordfight.jpg',
      img2: 'https://c4.wallpaperflare.com/wallpaper/620/551/594/animation-brave-disney-movie-wallpaper-preview.jpg',
      img3: 'https://m.media-amazon.com/images/M/MV5BMTQyMjI5ODE2MF5BMl5BanBnXkFtZTcwNTg0MTI3Nw@@._V1_.jpg',
    },
    youtubeId: 'TEHWDA_6e3M',
  },
  {
    name: 'Lightyear',
    description: 'While spending years attempting to return home, marooned Space Ranger Buzz Lightyear encounters an army of ruthless robots commanded by Zurg who are attempting to steal his fuel source.',
    cast: ['Chris Evans', 'Keke Palmer', 'Peter Sohn'],
    directors: ['Angus MacLane'],
    releaseYear: 2022,
    runtime: '1h 40m',
    tags: ['ActionAdventureDramaFamilySci-Fi'],
    imdbRating: 5.8,
    budget: '200 million USD',
    boxOffice: '225 million USD',
    productionCompany: ['Pixar Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://lumiere-a.akamaihd.net/v1/images/p_disney_lightyear_519_c4636841.jpeg',
    stills: {
      img1: 'https://www.bollywoodhungama.com/wp-content/uploads/2022/03/Pixar-restores-same-sex-kiss-in-Lightyear-after-backlash-from-LGBTQ-employees-at-Disney-studio-2.jpg',
      img2: 'https://static.wikia.nocookie.net/disney/images/7/7b/Lightyear_%28122%29.jpg',
      img3: 'https://static.wikia.nocookie.net/disney/images/9/99/Lightyear_-_teaser_%2826%29.jpg',
    },
    youtubeId: 'BwZs3H_UN3k',
  },
  {
    name: 'Encanto',
    description: 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.',
    cast: ['Stephanie Beatriz', 'María Cecilia Botero', 'John Leguizamo'],
    directors: ['Jared Bush', 'Byron Howard', 'Charise Castro Smith'],
    releaseYear: 2021,
    runtime: '1h 42m',
    tags: ['Comedy', 'Family', 'Fantasy', 'Musical'],
    imdbRating: 7.2,
    budget: '50 million USD',
    boxOffice: '256 million USD',
    productionCompany: ['Walt Disney Animation Studios', 'Walt Disney Pictures'],
    posterImg: 'https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NzM0LTkwOTYtMDI4MmNkMzIxODhkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg',
    stills: {
      img1: 'https://bleedingcool.com/wp-content/uploads/2021/07/ENCANTO-ONLINE-USE-teaser1_039.00_0283-1200x900.jpg',
      img2: 'https://media.cntraveler.com/photos/619bc7c149b1d4a10720e449/master/w_960,c_limit/Disney\'s%20Encanto_ENCANTO-ONLINE-USE-120_25_008.jpg',
      img3: 'https://cdn.theatlantic.com/thumbor/ACNpJlczfUcg8bbyPektdzx1dbw=/0x0:2500x1406/1600x900/media/img/mt/2022/01/ENCANTO_ONLINE_USE_mono_fullcomp.0050/original.jpg',
    },
    youtubeId: 'CaimKeDcudo',
  }
]

export default { movies, users }


// {
//   name: '',
//   description: '',
//   cast: [''],
//   directors: [''],
//   releaseYear: ,
//   runtime: '',
//   tags: [''],
//   imdbRating: ,
//   budget: '',
//   boxOffice: '',
//   productionCompany: [''],
//   posterImg: '',
//   stills: {
//     img1: '',
//     img2: '',
//     img3: '',
//   },
//   youtubeId: '',
// },